### ISSUE TITLE
p-tag margin in global message on Ikhaya

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-ubuntuusers#49]
I fixed it through the global style sheet for now, but the ikhaya.css defines

``` css
p {
    margin-bottom: .5em;
}
```

I added this to the global stylesheet:

``` css
.message.global p:last-of-type {
    margin-bottom: 0;
}
```
